npmScopes:
billing:
npmRegistryServer: "https://gitlab.zaytun.net/api/v4/projects/39/packages/npm"
npmRegistries:
//gitlab.zaytun.net/api/v4/projects/39/packages/npm:
npmAlwaysAuth: true
npmAuthToken: "U5in96YvKZAj_KZhE1Ms"
